apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: syncconfigs.sync.appuio.ch
spec:
  group: sync.appuio.ch
  names:
    kind: SyncConfig
    listKind: SyncConfigList
    plural: syncconfigs
    singular: syncconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deleteItems:
              items:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                type: object
              type: array
            forceRecreate:
              type: boolean
            items:
              items:
                type: object
              type: array
            namespaceSelector:
              properties:
                labelSelector:
                  type: object
                matchNames:
                  items:
                    type: string
                  type: array
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
