kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: espejo
subjects:
- kind: ServiceAccount
  name: $REPLACE_WITH_NAMESPACE
  namespace: syncer-test
roleRef:
  kind: ClusterRole
  name: espejo
  apiGroup: rbac.authorization.k8s.io
