kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: espejo
rules:
# Required for operator to function
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.appuio.ch
  resources:
  - '*'
  verbs:
  - '*'
# Required to sync objects
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - pods
  verbs:
  - "*"
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - networkpolicies
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
