apiVersion: apps/v1
kind: Deployment
metadata:
  name: espejo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: espejo
  template:
    metadata:
      labels:
        name: espejo
    spec:
      serviceAccountName: espejo
      containers:
        - name: espejo
          # Replace this with the built image name
          image: docker.io/vshn/espejo:v0.0.1
          command:
          - espejo
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "espejo"
