kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: espejo
subjects:
- kind: ServiceAccount
  name: espejo
roleRef:
  kind: Role
  name: espejo
  apiGroup: rbac.authorization.k8s.io
